package ru.gb.sklyarov.domain;

public enum CommandType {
    LS, MKDIR, DOWNLOAD, PRE_DOWNLOAD, UPLOAD, PRE_UPLOAD, AUTHENTICATION ,AUTHENTICATION_FAILED, AUTHENTICATION_SUCCESS,
    REGISTRATION, READY, ERROR
}
